version: '3.7'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  spring:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7333:7333
    depends_on:
      - redis

networks:
  default:
    external:
      name: arton-arch

