version: '3.7'

services:
  redis:
    image: redis
    ports:
      - 6378:6378

  spring:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8333:8333
    depends_on:
      - redis

networks:
  default:
    external:
      name: arton-arch

