spring:
  profiles:
    active: local
  jpa:
    show_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  bucket: arton
  full-bucket: https://arton.s3.ap-northeast-2.amazonaws.com/
  terms-dir: arton/terms
  password-mail-key: arton/mail/passwordResetMail.html

