spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  bucket: elasticbeanstalk-ap-northeast-2-629926164588
  full-bucket: https://elasticbeanstalk-ap-northeast-2-629926164588.s3.ap-northeast-2.amazonaws.com/
  default-image-local: /arton/image/default/default.png
  default-image: https://elasticbeanstalk-ap-northeast-2-629926164588.s3.ap-northeast-2.amazonaws.com/arton/image/default/default.jpeg
  root-dir: /arton/image/profiles
  terms-dir: arton/terms
  password-mail-key: arton/mail/passwordResetMail.html
  performance-dir: arton/image/performances