spring:
  profiles:
    active: test
  jpa:
    show_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  bucket: elasticbeanstalk-ap-northeast-2-629926164588
  full-bucket: https://elasticbeanstalk-ap-northeast-2-629926164588.s3.ap-northeast-2.amazonaws.com/
  terms-dir: arton/terms
  password-mail-key: arton/mail/passwordResetMail.html

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

